/* توصيل العاشر - التطبيق الرئيسي */
(function(){
'use strict';
let currentUser=null,currentOrderId=null,pickupMap=null,dropoffMap=null,trackMap=null,adminMap=null,pickupMarker=null,dropoffMarker=null;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=d=>d?new Date(d).toLocaleString('ar-EG'):''; const money=n=>Number(n||0).toFixed(2);
function toast(msg,type='success'){const e=$('toast');e.textContent=msg;e.className='toast '+type;clearTimeout(window._toast);window._toast=setTimeout(()=>e.className='toast hidden',3000)}
function modal(title,body,footer=''){ $('modal-title').textContent=title;$('modal-body').innerHTML=body;$('modal-footer').innerHTML=footer;$('modal').classList.remove('hidden'); }
function closeModal(){$('modal').classList.add('hidden')}
function showScreen(role){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(role+'-screen')?.classList.add('active');}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(page)?.classList.add('active');document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const t=$(page+'-title');if(t)$('admin-page-title').textContent=t.textContent||''; if(page==='admin-map')setTimeout(initAdminMap,100); if(page==='client-create')setTimeout(initOrderMaps,100); if(page==='client-track')setTimeout(renderTrack,100);}
async function refresh(){if(!currentUser)return; if(currentUser.role==='admin')await renderAdmin(); if(currentUser.role==='client')await renderClient(); if(currentUser.role==='courier')await renderCourier();}
async function init(){
 await DB.open(); await DB.seed();
 $('modal-close')?.addEventListener('click',closeModal); $('modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
 document.querySelectorAll('[data-page]').forEach(e=>e.addEventListener('click',ev=>{ev.preventDefault();go(e.dataset.page)}));
 document.querySelectorAll('.auth-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.auth-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.auth-form').forEach(x=>x.classList.remove('active'));$('login-form').classList.toggle('active',b.dataset.tab==='login');$('register-form').classList.toggle('active',b.dataset.tab==='register')}));
 $('login-form').addEventListener('submit',doLogin);$('register-form').addEventListener('submit',doRegister);$('admin-logout').addEventListener('click',logout);
 $('btn-create-order')?.addEventListener('click',()=>go('client-create'));$('btn-calc-order')?.addEventListener('click',calcOrder);$('create-order-form')?.addEventListener('submit',createOrder);$('courier-online-toggle')?.addEventListener('change',toggleCourier);
 $('admin-order-search')?.addEventListener('input',renderAdminOrders);$('admin-order-filter')?.addEventListener('change',renderAdminOrders);$('admin-client-search')?.addEventListener('input',renderAdminClients);$('admin-courier-search')?.addEventListener('input',renderAdminCouriers);$('admin-courier-status')?.addEventListener('change',renderAdminCouriers);
 setTimeout(()=>{const s=$('splash');if(s)s.style.display='none';$('app')?.classList.remove('hidden')},400);
}
async function doLogin(e){e.preventDefault();try{currentUser=await DB.login($('login-phone').value,$('login-password').value,$('login-role').value);localStorage.setItem('delivery_session',currentUser.sessionId);showScreen(currentUser.role);await refresh();toast('تم تسجيل الدخول');}catch(err){toast(err.message,'error')}}
async function doRegister(e){e.preventDefault();try{const role=$('reg-role').value;await DB.createUser({name:$('reg-name').value,phone:$('reg-phone').value,password:$('reg-password').value,role});toast('تم إنشاء الحساب ويمكنك تسجيل الدخول');e.target.reset();document.querySelector('[data-tab="login"]').click()}catch(err){toast(err.message,'error')}}
function logout(){currentUser=null;localStorage.removeItem('delivery_session');showScreen('auth');toast('تم تسجيل الخروج')}
async function renderAdmin(){
 const users=await DB.all('users'),orders=await DB.all('orders');
 $('admin-total-clients').textContent=users.filter(x=>x.role==='client').length;$('admin-total-couriers').textContent=users.filter(x=>x.role==='courier').length;
 $('admin-active-orders').textContent=orders.filter(x=>['pending','searching','accepted'].includes(x.status)).length;$('admin-completed-orders').textContent=orders.filter(x=>x.status==='completed').length;$('admin-cancelled-orders').textContent=orders.filter(x=>x.status==='cancelled').length;$('admin-total-revenue').textContent=money(orders.filter(x=>x.status==='completed').reduce((a,x)=>a+Number(x.cost||0),0));
 await renderAdminOrders();await renderAdminClients();await renderAdminCouriers();
 const today=new Date().toISOString().slice(0,10);const rows=orders.filter(x=>x.createdAt?.slice(0,10)===today);$('admin-today-orders').innerHTML=orderTable(rows,true)||empty('لا توجد طلبات اليوم');
}
const statusAr={pending:'بانتظار الموافقة',searching:'جاري البحث',accepted:'مقبول',completed:'مكتمل',cancelled:'ملغي'};
function empty(t){return `<div class="empty-state"><i class="fas fa-inbox"></i><p>${esc(t)}</p></div>`}
function orderTable(rows,compact=false){if(!rows.length)return '';return `<table><thead><tr><th>الطلب</th><th>العميل</th><th>الحالة</th><th>القيمة</th><th>التاريخ</th><th></th></tr></thead><tbody>${rows.map(o=>`<tr><td>#${esc(o.id.slice(-8))}</td><td>${esc(o.clientName||'-')}</td><td>${statusAr[o.status]||o.status}</td><td>${money(o.cost)} ج.م</td><td>${fmtDate(o.createdAt)}</td><td><button class="btn btn-sm btn-primary" onclick="window.adminOrder('${o.id}')">تفاصيل</button></td></tr>`).join('')}</tbody></table>`}
async function renderAdminOrders(){const all=await DB.all('orders'),q=($('admin-order-search')?.value||'').trim().toLowerCase(),f=$('admin-order-filter')?.value||'all';let rows=all.filter(o=>(f==='all'||o.status===f)&&(!q||String(o.id).toLowerCase().includes(q)||String(o.clientName).toLowerCase().includes(q))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('admin-orders-table').innerHTML=orderTable(rows)||empty('لا توجد طلبات')}
async function renderAdminClients(){const users=await DB.all('users'),q=($('admin-client-search')?.value||'').toLowerCase();const rows=users.filter(x=>x.role==='client'&&(!q||x.name.toLowerCase().includes(q)||x.phone.includes(q)));$('admin-clients-table').innerHTML=rows.length?`<table><thead><tr><th>الاسم</th><th>الهاتف</th><th>الحالة</th><th>التاريخ</th><th></th></tr></thead><tbody>${rows.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.phone)}</td><td>${u.status==='active'?'فعال':'موقوف'}</td><td>${fmtDate(u.createdAt)}</td><td><button class="btn btn-sm btn-outline" onclick="window.toggleUser('${u.id}')">${u.status==='active'?'إيقاف':'تفعيل'}</button></td></tr>`).join('')}</tbody></table>`:empty('لا يوجد عملاء')}
async function renderAdminCouriers(){const users=await DB.all('users'),q=($('admin-courier-search')?.value||'').toLowerCase(),f=$('admin-courier-status')?.value||'all';const rows=users.filter(x=>x.role==='courier'&&(!q||x.name.toLowerCase().includes(q)||x.phone.includes(q))&&(f==='all'||(f==='online'?x.online:!x.online)));$('admin-couriers-table').innerHTML=rows.length?`<table><thead><tr><th>الاسم</th><th>الهاتف</th><th>الاتصال</th><th>التقييم</th><th>المنجز</th><th></th></tr></thead><tbody>${rows.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.phone)}</td><td>${u.online?'متصل':'غير متصل'}</td><td>${u.rating||5}</td><td>${u.completedOrders||0}</td><td><button class="btn btn-sm btn-outline" onclick="window.toggleUser('${u.id}')">${u.status==='active'?'إيقاف':'تفعيل'}</button></td></tr>`).join('')}</tbody></table>`:empty('لا يوجد مندوبون')}
window.toggleUser=async id=>{const u=await DB.get('users',id);await DB.updateUser(id,{status:u.status==='active'?'suspended':'active'},currentUser.id);toast('تم تحديث حالة الحساب');refresh()};
window.adminOrder=async id=>{currentOrderId=id;const o=await DB.get('orders',id);if(!o)return;const couriers=(await DB.all('users')).filter(x=>x.role==='courier'&&x.status==='active');$('admin-order-details-content').innerHTML=`<div class="order-card"><h3>طلب #${esc(o.id.slice(-8))}</h3><p>العميل: ${esc(o.clientName)}</p><p>المستلم: ${esc(o.receiverName)} - ${esc(o.receiverPhone)}</p><p>الاستلام: ${esc(o.pickupAddress)}</p><p>التسليم: ${esc(o.dropoffAddress)}</p><p>القيمة: <b>${money(o.cost)} ج.م</b></p><p>الحالة: ${statusAr[o.status]}</p><div class="form-row"><button class="btn btn-success" onclick="window.approveOrder('${o.id}')">قبول الطلب</button><button class="btn btn-danger" onclick="window.cancelOrder('${o.id}')">رفض/إلغاء</button></div><hr><h4>تعيين مندوب</h4><select id="assign-courier"><option value="">اختر مندوباً</option>${couriers.map(c=>`<option value="${c.id}" ${o.courierId===c.id?'selected':''}>${esc(c.name)} - ${esc(c.phone)}</option>`).join('')}</select><button class="btn btn-primary" onclick="window.assignCourier('${o.id}')">تعيين</button></div>`;go('admin-order-details')};
window.approveOrder=async id=>{const o=await DB.get('orders',id);o.status='searching';o.updatedAt=DB.now();await DB.put('orders',o);await DB.notify(o.clientId,'تم قبول الطلب','تم قبول طلبك وبدأ البحث عن مندوب','success',{orderId:id});await DB.log(currentUser.id,'approve_order','قبول طلب',{orderId:id});toast('تم قبول الطلب');window.adminOrder(id)};
window.cancelOrder=async id=>{const o=await DB.get('orders',id);o.status='cancelled';o.updatedAt=DB.now();await DB.put('orders',o);await DB.notify(o.clientId,'تم إلغاء الطلب','تم إلغاء طلبك من الإدارة','warning',{orderId:id});await DB.log(currentUser.id,'cancel_order','إلغاء طلب',{orderId:id});toast('تم إلغاء الطلب');window.adminOrder(id)};
window.assignCourier=async id=>{const cid=$('assign-courier').value;if(!cid)return toast('اختر مندوباً','error');const o=await DB.get('orders',id);const c=await DB.get('users',cid);o.courierId=cid;o.courierName=c.name;o.status='accepted';o.updatedAt=DB.now();await DB.put('orders',o);await DB.notify(cid,'طلب جديد','تم تعيين طلب جديد لك',{orderId:id});await DB.notify(o.clientId,'تم تعيين مندوب','تم تعيين '+c.name+' لطلبك','info',{orderId:id});await DB.log(currentUser.id,'assign_courier','تعيين مندوب',{orderId:id,courierId:cid});toast('تم تعيين المندوب');window.adminOrder(id)};
function adminManagerUI(){modal('إنشاء حساب مدير',`<div class="form-group"><label>الاسم</label><input id="new-admin-name"></div><div class="form-group"><label>رقم الهاتف</label><input id="new-admin-phone" type="tel"></div><div class="form-group"><label>كلمة المرور</label><input id="new-admin-pass" type="password"></div><div class="form-group"><label>الحالة</label><select id="new-admin-status"><option value="active">فعال</option><option value="suspended">موقوف</option></select></div>`,`<button class="btn btn-outline" onclick="closeModal()">إلغاء</button><button class="btn btn-primary" onclick="window.createAdmin()">إنشاء</button>`)}
window.createAdmin=async()=>{try{const u=await DB.createUser({name:$('new-admin-name').value,phone:$('new-admin-phone').value,password:$('new-admin-pass').value,role:'admin',status:$('new-admin-status').value},currentUser.id);await DB.notify(u.id,'حساب المدير','تم إنشاء حساب مدير لك','success');closeModal();toast('تم إنشاء حساب المدير');renderAdminManagers()}catch(e){toast(e.message,'error')}};
async function renderAdminManagers(){const users=(await DB.all('users')).filter(x=>x.role==='admin');let box=$('admin-managers-table');if(!box)return;box.innerHTML=`<table><thead><tr><th>الاسم</th><th>الهاتف</th><th>الحالة</th><th>الإنشاء</th><th>إجراءات</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.phone)}</td><td>${u.status==='active'?'فعال':'موقوف'}</td><td>${fmtDate(u.createdAt)}</td><td><button class="btn btn-sm btn-outline" onclick="window.editAdmin('${u.id}')">تعديل</button> <button class="btn btn-sm btn-danger" onclick="window.removeAdmin('${u.id}')">حذف</button></td></tr>`).join('')}</tbody></table>`}
window.editAdmin=async id=>{const u=await DB.get('users',id);modal('تعديل المدير',`<div class="form-group"><label>الاسم</label><input id="ea-name" value="${esc(u.name)}"></div><div class="form-group"><label>الهاتف</label><input id="ea-phone" value="${esc(u.phone)}"></div><div class="form-group"><label>كلمة مرور جديدة (اختياري)</label><input id="ea-pass" type="password"></div><div class="form-group"><label>الحالة</label><select id="ea-status"><option value="active" ${u.status==='active'?'selected':''}>فعال</option><option value="suspended" ${u.status!=='active'?'selected':''}>موقوف</option></select></div>`,`<button class="btn btn-outline" onclick="closeModal()">إلغاء</button><button class="btn btn-primary" onclick="window.saveAdmin('${id}')">حفظ</button>`)};
window.saveAdmin=async id=>{try{const p={name:$('ea-name').value,phone:$('ea-phone').value,status:$('ea-status').value};if($('ea-pass').value)p.password=$('ea-pass').value;await DB.updateUser(id,p,currentUser.id);closeModal();toast('تم الحفظ');renderAdminManagers()}catch(e){toast(e.message,'error')}};
window.removeAdmin=async id=>{if(!confirm('حذف حساب المدير؟'))return;try{await DB.deleteUser(id,currentUser.id);toast('تم الحذف');renderAdminManagers()}catch(e){toast(e.message,'error')}};
async function renderClient(){const orders=(await DB.all('orders')).filter(x=>x.clientId===currentUser.id);$('client-name').textContent=currentUser.name;$('client-completed').textContent=orders.filter(x=>x.status==='completed').length;$('client-active').textContent=orders.filter(x=>!['completed','cancelled'].includes(x.status)).length;$('client-cancelled').textContent=orders.filter(x=>x.status==='cancelled').length;$('client-recent-orders').innerHTML=orderCards(orders.slice(-5).reverse());const cur=orders.find(x=>!['completed','cancelled'].includes(x.status));$('client-current-order').innerHTML=cur?orderCard(cur):empty('لا يوجد طلب جاري حالياً');$('client-orders-list').innerHTML=orderCards(orders.reverse());await renderNotifications()}
function orderCard(o){return `<div class="order-card" onclick="window.clientOrder('${o.id}')"><b>#${esc(o.id.slice(-8))}</b><span>${statusAr[o.status]}</span><p>${esc(o.pickupAddress)} ← ${esc(o.dropoffAddress)}</p><strong>${money(o.cost)} ج.م</strong></div>`}function orderCards(a){return a.length?a.map(orderCard).join(''):empty('لا توجد طلبات')}
window.clientOrder=async id=>{currentOrderId=id;const o=await DB.get('orders',id);$('order-id-title').textContent='#'+o.id.slice(-8);$('order-details-content').innerHTML=`<div class="order-card"><p><b>الحالة:</b> ${statusAr[o.status]}</p><p><b>الاستلام:</b> ${esc(o.pickupAddress)}</p><p><b>التسليم:</b> ${esc(o.dropoffAddress)}</p><p><b>المستلم:</b> ${esc(o.receiverName)} - ${esc(o.receiverPhone)}</p><p><b>المندوب:</b> ${esc(o.courierName||'لم يتم التعيين')}</p><p><b>التكلفة:</b> ${money(o.cost)} ج.م</p><button class="btn btn-primary" onclick="go('client-track')">تتبع الطلب</button>${!['completed','cancelled'].includes(o.status)?`<button class="btn btn-danger" onclick="window.clientCancel('${o.id}')">إلغاء الطلب</button>`:''}</div>`;go('client-order-details')};
window.clientCancel=async id=>{const o=await DB.get('orders',id);if(o.status==='completed')return; o.status='cancelled';o.updatedAt=DB.now();await DB.put('orders',o);await DB.log(currentUser.id,'client_cancel','إلغاء من العميل',{orderId:id});if(o.courierId)await DB.notify(o.courierId,'إلغاء طلب','تم إلغاء الطلب',{orderId:id});toast('تم إلغاء الطلب');await refresh();go('client-orders')};
async function renderNotifications(){const n=(await DB.all('notifications')).filter(x=>x.userId===currentUser.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('client-notif-count').textContent=n.filter(x=>!x.read).length;$('client-notif-list').innerHTML=n.length?n.map(x=>`<div class="notif-item ${x.read?'':'unread'}" onclick="window.readNotif('${x.id}')"><b>${esc(x.title)}</b><p>${esc(x.message)}</p><small>${fmtDate(x.createdAt)}</small></div>`).join(''):empty('لا توجد إشعارات')}
window.readNotif=async id=>{const n=await DB.get('notifications',id);n.read=true;await DB.put('notifications',n);renderNotifications()};
async function renderCourier(){const u=await DB.get('users',currentUser.id);currentUser=u;$('courier-name').textContent=u.name;$('courier-status-text').textContent=u.online?'متصل':'غير متصل';$('courier-online-toggle').checked=!!u.online;const orders=await DB.all('orders');const mine=orders.filter(x=>x.courierId===u.id),avail=orders.filter(x=>['searching','pending'].includes(x.status)&&!x.courierId);$('courier-earnings').textContent=money(u.earnings);$('courier-done').textContent=u.completedOrders||mine.filter(x=>x.status==='completed').length;$('courier-rating').textContent=u.rating||5;$('courier-current-order').innerHTML=orderCard(mine.find(x=>['accepted'].includes(x.status))||{})||empty('لا يوجد طلب حالياً');$('courier-available-orders').innerHTML=avail.map(o=>`<div class="order-card"><b>#${o.id.slice(-8)}</b><p>${esc(o.pickupAddress)} ← ${esc(o.dropoffAddress)}</p><strong>${money(o.cost)} ج.م</strong><button class="btn btn-primary" onclick="window.acceptCourierOrder('${o.id}')">قبول الطلب</button></div>`).join('')||empty('لا توجد طلبات متاحة');$('courier-orders-list').innerHTML=orderCards(mine)}
async function toggleCourier(e){const u=await DB.get('users',currentUser.id);u.online=e.target.checked;u.updatedAt=DB.now();await DB.put('users',u);currentUser=u;toast(u.online?'أصبحت متصلاً':'أصبحت غير متصل');renderCourier()}
window.acceptCourierOrder=async id=>{const o=await DB.get('orders',id);if(o.courierId&&o.courierId!==currentUser.id)return toast('الطلب تم أخذه','error');o.courierId=currentUser.id;o.courierName=currentUser.name;o.status='accepted';o.updatedAt=DB.now();await DB.put('orders',o);await DB.notify(o.clientId,'تم قبول الطلب','المندوب '+currentUser.name+' قبل طلبك','success',{orderId:id});await DB.log(currentUser.id,'accept_order','قبول طلب مندوب',{orderId:id});toast('تم قبول الطلب');renderCourier()};
function calcOrder(){const a=$('pickup-address').value,b=$('dropoff-address').value;if(!a||!b)return toast('أدخل عنواني الاستلام والتسليم','error');const distance=5;const cost=20+distance*8;$('sum-distance').textContent=distance+' كم';$('sum-cost').textContent=money(cost)+' ج.م';$('sum-payment').textContent=document.querySelector('input[name=payment]:checked').value==='cash'?'نقداً':'محفظة';$('order-summary').style.display='block';$('btn-confirm-order').disabled=false;window._orderCost=cost;window._orderDistance=distance}
async function createOrder(e){e.preventDefault();if($('btn-confirm-order').disabled)return;const o={id:DB.uid('ORD'),clientId:currentUser.id,clientName:currentUser.name,status:'pending',pickupAddress:$('pickup-address').value,pickupLat:Number($('pickup-lat').value||30.2989),pickupLng:Number($('pickup-lng').value||31.7414),dropoffAddress:$('dropoff-address').value,dropoffLat:Number($('dropoff-lat').value||30.31),dropoffLng:Number($('dropoff-lng').value||31.75),receiverName:$('receiver-name').value,receiverPhone:$('receiver-phone').value,packageType:$('package-type').value,packageDesc:$('package-desc').value,weight:Number($('package-weight').value||1),size:$('package-size').value,notes:$('order-notes').value,payment:document.querySelector('input[name=payment]:checked').value,distance:window._orderDistance||5,cost:window._orderCost||60,createdAt:DB.now(),updatedAt:DB.now()};await DB.put('orders',o);await DB.log(currentUser.id,'create_order','إنشاء طلب',{orderId:o.id});const admins=(await DB.all('users')).filter(x=>x.role==='admin'&&x.status==='active');for(const a of admins)await DB.notify(a.id,'طلب جديد','تم إنشاء طلب جديد #'+o.id.slice(-8),'info',{orderId:o.id});toast('تم إنشاء الطلب');e.target.reset();$('order-summary').style.display='none';$('btn-confirm-order').disabled=true;await refresh();go('client-order-details');window.clientOrder(o.id)}
function initOrderMaps(){if(typeof L==='undefined')return;const center=[30.2989,31.7414];if(!pickupMap){pickupMap=L.map('pickup-map').setView(center,12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(pickupMap);pickupMap.on('click',e=>{if(pickupMarker)pickupMap.removeLayer(pickupMarker);pickupMarker=L.marker(e.latlng).addTo(pickupMap);$('pickup-lat').value=e.latlng.lat;$('pickup-lng').value=e.latlng.lng})}if(!dropoffMap){dropoffMap=L.map('dropoff-map').setView(center,12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(dropoffMap);dropoffMap.on('click',e=>{if(dropoffMarker)dropoffMap.removeLayer(dropoffMarker);dropoffMarker=L.marker(e.latlng).addTo(dropoffMap);$('dropoff-lat').value=e.latlng.lat;$('dropoff-lng').value=e.latlng.lng})}setTimeout(()=>{pickupMap.invalidateSize();dropoffMap.invalidateSize()},200)}
function renderTrack(){if(typeof L==='undefined'||!currentOrderId)return;DB.get('orders',currentOrderId).then(o=>{if(!o)return;if(!trackMap){trackMap=L.map('track-map').setView([o.pickupLat,o.pickupLng],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(trackMap)}L.marker([o.pickupLat,o.pickupLng]).addTo(trackMap).bindPopup('الاستلام');L.marker([o.dropoffLat,o.dropoffLng]).addTo(trackMap).bindPopup('التسليم');$('track-info').innerHTML=`<div class="order-card"><b>الحالة: ${statusAr[o.status]}</b><p>المندوب: ${esc(o.courierName||'لم يتم التعيين')}</p></div>`;setTimeout(()=>trackMap.invalidateSize(),200)})}
function initAdminMap(){if(typeof L==='undefined'||adminMap)return;adminMap=L.map('admin-map-container').setView([30.2989,31.7414],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(adminMap);DB.all('users').then(users=>users.filter(x=>x.role==='courier'&&x.online).forEach(u=>{if(u.lat&&u.lng)L.marker([u.lat,u.lng]).addTo(adminMap).bindPopup(u.name)}));}
// إضافة إدارة المديرين للقائمة حتى لو لم تكن موجودة في HTML الأصلي
function injectAdminManagers(){const nav=document.querySelector('#admin-sidebar .sidebar-nav');if(nav&&!$('nav-admin-managers')){const b=document.createElement('button');b.id='nav-admin-managers';b.className='side-item';b.dataset.page='admin-managers';b.innerHTML='<i class="fas fa-user-shield"></i> إدارة المديرين';b.onclick=()=>go('admin-managers');nav.insertBefore(b,nav.querySelector('#admin-logout'));const s=document.createElement('section');s.id='admin-managers';s.className='page';s.innerHTML='<div class="page-header"><h2>إدارة المديرين</h2><button class="btn btn-primary" onclick="adminManagerUI()"><i class="fas fa-user-plus"></i> إنشاء حساب مدير</button></div><div id="admin-managers-table" class="table-responsive"></div>';$('admin-screen').querySelector('.admin-content').appendChild(s)}}
window.addEventListener('DOMContentLoaded',async()=>{injectAdminManagers();await init()});window.go=go;window.closeModal=closeModal;window.adminManagerUI=adminManagerUI;
})();
